"""add cluster.insecure

Revision ID: 3dd28d5360e5
Revises: 65f848049163
Create Date: 2026-06-11 09:24:03.743354
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '3dd28d5360e5'
down_revision: Union[str, None] = '65f848049163'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clusters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('insecure', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clusters', schema=None) as batch_op:
        batch_op.drop_column('insecure')

    # ### end Alembic commands ###
