"""initial schema

Revision ID: 65f848049163
Revises: 
Create Date: 2026-06-10 10:26:54.066716
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '65f848049163'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clusters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('context', sa.String(length=255), nullable=False),
    sa.Column('server', sa.String(length=512), nullable=True),
    sa.Column('provider', sa.String(length=128), nullable=True),
    sa.Column('version', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('favorite', sa.Boolean(), nullable=False),
    sa.Column('kubeconfig_path', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('clusters', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clusters_context'), ['context'], unique=True)

    op.create_table('command_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cluster_id', sa.Integer(), nullable=True),
    sa.Column('context', sa.String(length=255), nullable=True),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('target', sa.String(length=512), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('command_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_command_history_cluster_id'), ['cluster_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('command_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_command_history_cluster_id'))

    op.drop_table('command_history')
    with op.batch_alter_table('clusters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clusters_context'))

    op.drop_table('clusters')
    # ### end Alembic commands ###
