"""add cluster.color

Revision ID: a56ba4a12ec7
Revises: 3dd28d5360e5
Create Date: 2026-06-11 09:34:46.785607
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a56ba4a12ec7'
down_revision: Union[str, None] = '3dd28d5360e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clusters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('color', sa.String(length=7), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clusters', schema=None) as batch_op:
        batch_op.drop_column('color')

    # ### end Alembic commands ###
