"""context not unique

Revision ID: f30cb007a222
Revises: a56ba4a12ec7
Create Date: 2026-06-11 11:49:21.977743
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'f30cb007a222'
down_revision: Union[str, None] = 'a56ba4a12ec7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clusters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clusters_context'))
        batch_op.create_index(batch_op.f('ix_clusters_context'), ['context'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clusters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clusters_context'))
        batch_op.create_index(batch_op.f('ix_clusters_context'), ['context'], unique=1)

    # ### end Alembic commands ###
